const ethosData = [
      {emoji: '⚔️', title: 'Militaristic', description: 'Values strength, combat prowess, and military discipline.', opposites: ['Pacifist']},
      {emoji: '🕊️', title: 'Pacifist', description: 'Values peace, diplomacy, and non-violence.', opposites: ['Militaristic']},
      {emoji: '🤝', title: 'Communal', description: 'The group is more important than the individual.', opposites: ['Individualist']},
      {emoji: '👤', title: 'Individualist', description: 'Values personal freedom, self-reliance, and individual achievement.', opposites: ['Communal']},
      {emoji: '❤️', title: 'Xenophilic', description: 'Fascinated by and open to foreign cultures and peoples.', opposites: ['Xenophobic']},
      {emoji: '😠', title: 'Xenophobic', description: 'Fearful or hateful of foreign cultures and peoples.', opposites: ['Xenophilic']},
      {emoji: '⚖️', title: 'Equalist', description: 'Strives for equality among all members.', opposites: ['Hierarchical']},
      {emoji: '🏰', title: 'Hierarchical', description: 'Society is rigidly structured with clear levels of power and status.', opposites: ['Equalist']},
      {emoji: '🔬', title: 'Progressive', description: 'Embraces innovation, change, and new ideas.', opposites: ['Traditional']},
      {emoji: '🏛️', title: 'Traditional', description: 'Reveres the ways of ancestors and maintains ancient customs.', opposites: ['Progressive']},
      {emoji: '🙏', title: 'Spiritual', description: 'Deeply connected to religious or philosophical beliefs.', opposites: ['Materialist']},
      {emoji: '💰', title: 'Materialist', description: 'Values wealth, commerce, and the acquisition of possessions.', opposites: ['Spiritual']},
      {emoji: '📜', title: 'Bureaucratic', description: 'A highly organized society that values order and procedure.', opposites: ['Charismatic']},
      {emoji: '🎭', title: 'Charismatic', description: 'Values personal charm, influence, and social skill.', opposites: ['Bureaucratic']}
    ];

    // Traditions Data
    const traditionData = [
      {
        name: 'Military & Defense',
        emoji: '🛡️',
        color: '#EF4444',
        traditions: [
          {name: 'Swift Raiders', emoji: '💨', description: 'Specializes in quick strikes and evasive maneuvers in combat, ideal for raiding or guerilla warfare.', opposite: 'Unyielding Stand'},
          {name: 'Warrior Esteem', emoji: '💪', description: 'Greatly respects and celebrates martial prowess and warriors, with combat skills being a path to high status.'},
          {name: 'Chivalrous Code', emoji: '🛡️', description: 'Adheres to a strict code of honor, courtesy, and bravery, especially in combat and interactions with defeated foes.'},
          {name: 'Coastal Guard', emoji: '🌊', description: 'Fighters specialized in naval combat or the defense of coastlines against seaborne threats.'},
          {name: 'Conquest Ethos', emoji: '🗡️', description: 'Believes in resolving disputes or gaining power through force, valuing conquest and military might.'},
          {name: 'Desert Warriors', emoji: '🏜️', description: 'Fighters adept at warfare in arid or desert environments, mastering survival and combat in harsh conditions.'},
          {name: 'Steadfast Defense', emoji: '🧱', description: 'Known for their unwavering defense and ability to hold ground against overwhelming odds, often in fortified positions.'},
          {name: 'Adaptive Tactics', emoji: '🏃', description: 'Skilled in flexible, mobile warfare, adapting to changing battle conditions and utilizing their environment.'},
          {name: 'Highland Fighters', emoji: '⛰️', description: 'Specializes in guerrilla tactics and fighting in mountainous terrain, using the landscape to their advantage.'},
          {name: 'Unyielding Stand', emoji: '🔥', description: 'Prefers direct, head-on confrontation over retreating or complex tactics, valuing courage and endurance in battle.', opposite: 'Swift Raiders'},
          {name: 'Ritual Duels', emoji: '⚔️', description: 'Emphasizes single combat or duels as a key part of warfare or honor, often preceding larger battles or resolving disputes.'},
          {name: 'Forest Combatants', emoji: '🌲', description: 'Adept at combat within dense forests and woodland environments, utilizing stealth and ambush tactics.'},
          {name: 'Irritable', emoji: '😠', description: 'Prone to disputes and conflicts, both internally and externally, often leading to frequent skirmishes.'},
          {name: 'Militarized', emoji: '🏹', description: 'Society is heavily structured around military values and fighting prowess, with military service being a core duty.'},
          {name: 'Loyal Troops', emoji: '🫡', description: 'Their military forces are known for their unwavering loyalty and discipline, especially to their commanders or state.'},
          {name: 'Mercenary Blades', emoji: '💰', description: 'Provides mercenary services, with skilled warriors available for payment, often leading to a renowned mercenary tradition.'},
          {name: 'Chariot Lords', emoji: '🐎', description: 'Specializes in the use of light or heavy chariots for combat, known for rapid assaults and devastating charges.'},
          {name: 'Hill Fortification', emoji: '⛰️', description: 'Focuses on building easily defensible settlements on elevated terrain, making them difficult to conquer.'},
          {name: 'Bronze Phalanx', emoji: '🛡️', description: 'Emphasizes disciplined formations using long bronze spears, creating an impenetrable wall of shields.'},
          {name: 'Siege Craft', emoji: '🚧', description: 'Develops advanced techniques and equipment for breaching fortified positions and conducting sieges.'},
          {name: 'Imperial Discipline', emoji: '🛡️', description: 'The military organization of the old Parsavid Empire is still in living memory within this culture. A professional army is favored over levied troops.'},
          {name: 'Battlefield Scavengers', emoji: '🥷', description: 'Their armies are adept at salvaging resources and equipment from defeated foes and battlefields, reducing supply strain.'},
          {name: 'Drilled Formations', emoji: '🛡️', description: 'Excels in disciplined, coordinated military formations, emphasizing unit cohesion and strategic movement.'},
          {name: 'Archery Tradition', emoji: '🏹', description: 'Archery is a highly valued skill, with regular competitions fostering excellence in longbow use for hunting and warfare.'},
          {name: 'Flexible Invaders', emoji: '🌀', description: 'Highly adaptable military, capable of changing tactics and strategies rapidly to overcome diverse defenses and environments.'},
          {name: 'Strength Cult', emoji: '💪', description: 'A martial philosophy emphasizing individual strength and prowess, with leaders and warriors earning their position through combat ability.'},
          {name: 'Veteran Honoring', emoji: '🎖️', description: 'Experienced warriors and military veterans are highly honored and respected, often serving as advisors or mentors.'},
          {name: 'Numerical Superiority', emoji: '👨‍👩‍👧‍👦', description: 'Relies on overwhelming numerical superiority in battle, emphasizing mass mobilization and large armies.'},
          {name: 'Priest Warriors', emoji: '✨⚔️', description: 'Religious figures who also serve as warriors and military leaders, blending spiritual devotion with martial skill.'},
          {name: 'Meritocratic Army', emoji: '🏆', description: 'Status and leadership in the military are earned through demonstrated skill and achievement rather than birthright.'},
          {name: 'Winter Fighters', emoji: '❄️', description: 'Specialized in combat and survival in cold, snowy conditions, utilizing winter as a strategic advantage.'},
          {name: 'Bold Cadets', emoji: '🌟', description: 'Young recruits are encouraged to display bold initiative and daring tactics, fostering aggressive leadership.'},
          {name: 'Fortress Defense', emoji: '🛡️', description: 'Excels at fortifying positions and employing strategies focused on holding ground and wearing down invaders.'},
          {name: 'Frontier Guards', emoji: '🌲⚔️', description: 'Experienced fighters accustomed to defending and expanding borders against external threats and wilderness dangers.'},
          {name: 'Elite Regiments', emoji: '🏛️🛡️', description: 'Maintains elite, highly disciplined military units, reminiscent of a powerful historical empire, forming a core professional army.'},
          {name: 'Unyielding Spirit', emoji: '🔥', description: 'Known for their unwavering courage and resilience in battle, inspired by a legendary figure or historical event.'},
          {name: 'Royal Host', emoji: '👑', description: 'A standing professional army directly loyal to the monarch, providing a centralized and powerful military force.'},
          {name: 'Warrior Queens', emoji: '👸⚔️', description: 'Female leaders and rulers are expected to be skilled in warfare and lead their armies into battle.'},
          {name: 'Jungle Fighters', emoji: '🌿', description: 'Specializes in combat and survival within dense jungle environments, mastering the terrain for ambush.'},
        ]
      },
      {
        name: 'Social & Governance',
        emoji: '🤝',
        color: '#22C55E',
        traditions: [
          {name: 'Shared Lands', emoji: '🌱', description: 'Land and resources are owned and managed communally, fostering shared responsibility and egalitarianism.'},
          {name: 'Court Eunuchs', emoji: '🧑‍⚖️', description: 'Utilizes eunuchs in high-ranking administrative or court positions, often for their perceived loyalty and impartiality.', required: {ethics: ['Bureaucratic']}},
          {name: 'Cultural Fusion', emoji: '🌐', description: 'Actively integrates and adopts aspects from other cultures, leading to a diverse and evolving societal fabric.'},
          {name: 'Generous Spirit', emoji: '❤️', description: 'Strong emphasis on generosity, giving to the poor, and mutual aid within the community and beyond.'},
          {name: 'Local Customs', emoji: '🏘️', description: 'Strong loyalty to local community or region, sometimes to the exclusion of outsiders, valuing local customs above all.'},
          {name: 'Community Assembly', emoji: '🗣️', description: 'A tradition of communal assemblies or councils for decision-making, where all members have a voice.'},
          {name: 'Clan Unity', emoji: '🔗', description: 'Society is organized around strong tribal bonds and collective action, with lineage playing a key role.'},
          {name: 'Strict Isolation', emoji: '🚫', description: 'Prefers to remain separate from other cultures and external affairs, prioritizing self-sufficiency and purity.', opposite: 'Open Embrace'},
          {name: 'Ancient Traditions', emoji: '🕰️', description: 'Highly resistant to change, valuing ancient customs and ways as the foundation of their society.'},
          {name: 'Hospitality', emoji: '☕', description: 'Places immense value on welcoming and protecting guests, with hospitality being a sacred duty.'},
          {name: 'Equal Inheritance', emoji: '👨‍👩‍👧‍👦', description: 'Property and titles are divided equally among all children, regardless of gender, promoting broad family welfare.'},
          {name: 'Hereditary Ranks', emoji: '🧬', description: 'Social status and power are primarily determined by birthright, with distinct noble and common classes.'},
          {name: 'Public Honor', emoji: '🎭', description: 'Honor is maintained through public displays, rituals, or challenges, often involving elaborate ceremonies.'},
          {name: 'Open Embrace', emoji: '🌍', description: 'Open to foreign influences and peoples, often integrating them into their society and embracing diversity.', opposite: 'Strict Isolation'},
          {name: 'Elder Council', emoji: '👴', description: 'Respects and seeks guidance from wise and experienced elders in social and policy matters.'},
          {name: 'Divine Rule', emoji: '👑✨', description: 'Religious authorities exert significant influence on the moral and legal decisions of the society and its leaders.'},
          {name: 'Vassal Oaths', emoji: '🤝', description: 'Formalized pledges of loyalty and service between less powerful groups and dominant patrons or overlords.'},
          {name: 'Codified Laws', emoji: '🏛️', description: 'Laws are meticulously written down in formal legal codes, often carved in stone or inscribed on tablets, accessible to the public.'},
          {name: 'Master Diplomats', emoji: '🤝', description: 'Highly skilled in negotiation and foreign relations, often resolving conflicts without resorting to warfare.'},
          {name: 'Strict Legalism', emoji: '⚖️', description: 'Society is deeply governed by complex laws and legal interpretations, valuing order and adherence to rules.'},
          {name: 'Compliant Populace', emoji: '👥', description: 'The populace is generally adaptable and compliant, readily accepting changes in governance or social norms.'},
          {name: 'Matriarchal Society', emoji: '♀️', description: 'Society is organized around female leadership, with women holding primary power in families, governance, and spiritual roles.'},
          {name: 'Court Intrigue', emoji: '🤫', description: 'Courtly life is dominated by intricate power struggles, alliances, and betrayals among the elite.'},
          {name: 'Republican Heritage', emoji: '🏛️', description: 'Influenced by an ancient republican system, valuing civic participation, elected officials, and a balance of power.'},
          {name: 'Noble Caste', emoji: '👑', description: 'Society is rigidly structured with a distinct and powerful hereditary upper class that holds political and social control.'},
          {name: 'Ransom Practice', emoji: '🤝💰', description: 'A practice of negotiating and paying ransoms for captured enemies or territories rather than protracted warfare.'},
          {name: 'Guest Code', emoji: '😊', description: 'Known for their open and friendly disposition towards strangers and foreigners, encouraging cultural exchange.'},
          {name: 'Hedonistic Feasts', emoji: '🎉', description: 'Values extravagant feasts and celebrations, focusing on pleasure, indulgence, and sensory experiences.'},
          {name: 'Diaspora Identity', emoji: '🌐', description: 'A culture characterized by its dispersion from an original homeland, maintaining identity across various settlements.'},
          {name: 'Equitable Law', emoji: '⚖️', description: 'Strives for fairness and impartiality in all social and legal matters, ensuring justice for all citizens.'},
          {name: 'Enlightened Nobles', emoji: '🧠👑', description: 'Powerful nobles and leaders are also patrons of arts, sciences, and philosophy, fostering intellectual growth.'},
          {name: 'Retributive Justice', emoji: '👁️', description: 'Legal system based on retributive justice, where punishment mirrors the offense.'},
          {name: 'Patient Demeanor', emoji: '😌', description: 'Characterized by patience, tolerance, and restraint, especially in dealing with internal dissent or external provocations.'},
          {name: 'Jokers', emoji: '😂', description: 'A lighthearted and jovial culture that finds humor in everyday life, often using satire and wit.'},
          {name: 'Loyal Citizenry', emoji: '👑', description: 'The populace exhibits profound loyalty to their ruler or governing body, upholding stability and order.'},
          {name: 'Modest Lifestyle', emoji: '👚', description: 'Emphasizes humility, simplicity, and restraint in dress, behavior, and display of wealth.'},
          {name: 'Peace Advocates', emoji: '🕊️', description: 'Strongly averse to warfare and violence, preferring diplomatic solutions and peaceful coexistence.'},
          {name: 'Philosophical Tradition', emoji: '🤔', description: 'Society places a high value on intellectual inquiry, critical thinking, and the pursuit of wisdom.'},
          {name: 'Dominion Drive', emoji: '😈', description: 'Driven by an insatiable desire for dominance and control, constantly seeking to expand their influence.'},
          {name: 'Ritual Friendships', emoji: '🤝', description: 'Establishes strong bonds and alliances with other cultures through elaborate ceremonies and shared customs.'},
          {name: 'Meritocratic System', emoji: '🏅', description: 'Individuals are granted the opportunity to demonstrate their worth and ability to rise in society, regardless of their background.'},
          {name: 'Trial by Combat', emoji: '⚔️', description: 'Legal disputes are resolved through single combat where divine judgment is believed to determine the victor.'},
          {name: 'Concubine System', emoji: '💖', description: 'A recognized practice where individuals, typically women, live with a person of higher status without being fully married, often holding a specific social role.'},
          {name: 'Frequent Festivals', emoji: '🎉', description: 'Society celebrates numerous festivals and holidays throughout the year, emphasizing communal joy and traditions.'},
          {name: 'Gruesome Law', emoji: '🙈', description: 'A severe form of punishment or political incapacitation involving blinding, considered more merciful than execution.'},
          {name: 'Monogamy Practice', emoji: '💍', description: 'Marriage is strictly limited to one spouse at a time, emphasizing fidelity and exclusive partnerships.'},
          {name: 'Polygamy Practice', emoji: '💍💍', description: 'Marriage allows for multiple spouses, often with specific rules regarding the number of spouses and their social standing.'},
          {name: 'Nyssene Tolerance', emoji: '🦁', description: 'The Nyssene people sitting at the heart of the Peshtar sea saw empires come and go, friends or foes, enslavers or liberators, all of them bringing their different foreign customs, and they learned to adapt.'},
          {name: 'Elder Assemblies', emoji: '🗣️', description: 'Decision-making through a traditional assembly of elders or respected community members, emphasizing consensus and local autonomy.'},
          {name: 'Steppe Openness', emoji: '🐎🌍', description: 'A cultural openness and adaptability, common among nomadic steppe peoples, that allows them to interact and integrate with diverse groups encountered during their migrations.'}
        ]
      },
      {
        name: 'Economy & Resources',
        emoji: '💰',
        color: '#EAB308',
        traditions: [
          {name: 'Thrifty Smiths', emoji: '🛠️', description: 'Known for producing efficient and cost-effective armor and weapons, optimizing resource use.'},
          {name: 'Horse Breeders', emoji: '🐎', description: 'Specializes in breeding and training horses, often for cavalry, agriculture, or trade, a source of wealth.'},
          {name: 'Agrarian Society', emoji: '🌾', description: 'Economy and lifestyle are primarily based on farming and agriculture, with deep ties to the land.', opposite: 'Maritime Merchants'},
          {name: 'Caravan Masters', emoji: '🐪', description: 'Proficient in long-distance trade via caravans, traversing vast territories and connecting distant markets.'},
          {name: 'Maritime Merchants', emoji: '🚢', description: 'Economy heavily relies on sea trade and mercantile activities, with extensive overseas networks.', opposite: 'Agrarian Society'},
          {name: 'Dryland Survival', emoji: '💧', description: 'Developed unique methods for survival and sustenance in arid regions, mastering water conservation.'},
          {name: 'Clan Economy', emoji: '👨‍👧‍👦', description: 'Economic activities are primarily conducted and passed down through families, strengthening lineage bonds.'},
          {name: 'Terrace Farming', emoji: '🪜', description: 'Utilizes terraced fields for agriculture in hilly or mountainous areas, maximizing arable land and controlling erosion.'},
          {name: 'Tin Road Traders', emoji: '🛣️', description: 'Dominates ancient trade routes specializing in tin, vital for bronze production and a source of great wealth.'},
          {name: 'Copper Lords', emoji: '⛏️', description: 'Controls significant copper mining operations and smelting techniques, key to their metallurgical prowess.'},
          {name: 'Obsidian Crafters', emoji: '🔪', description: 'Renowned for trading and crafting sharp tools and weapons from obsidian, a valuable trade commodity.'},
          {name: 'Amber Merchants', emoji: '💎', description: 'Engages in long-distance trade of amber, prized for adornment, mystical properties, and its rarity.'},
          {name: 'Cattle Herders', emoji: '🐄', description: 'Wealth and status are primarily measured by the size and health of livestock herds, fundamental to their economy.'},
          {name: 'Seasonal Fishing', emoji: '🎣', description: 'Relies heavily on seasonal fishing migrations for sustenance and trade, adapting their lifestyle to aquatic cycles.'},
          {name: 'River Barges', emoji: '🛶', description: 'Utilizes large river barges for efficient transportation of goods along waterways, dominating internal trade.'},
          {name: 'Grain Silos', emoji: '🍞', description: 'Specializes in constructing massive, durable structures for long-term grain storage, ensuring food security.'},
          {name: 'Olive Oil Cultivation', emoji: '🫒', description: 'Cultivates olives extensively for oil, a key commodity for food, light, and trade across their lands.'},
          {name: 'Vineyard Cultivation', emoji: '🍇', description: 'Focuses on grape cultivation and wine production as a significant economic activity, with wine as a trade good.'},
          {name: 'Salt Production', emoji: '🧂', description: 'Known for large-scale salt harvesting or mining, essential for food preservation, trade, and ritual.'},
          {name: 'Ancient Miners', emoji: '⛏️', description: 'Skilled in extracting resources from the earth, particularly metals, contributing to military logistics and weaponcraft.'},
          {name: 'Pastoral Nomads', emoji: '🐑', description: 'A society whose economy and way of life are centered around raising and herding livestock.'},
          {name: 'Skilled Metalworkers', emoji: '⚒️', description: 'Highly skilled in metallurgy, producing fine tools, weapons, and decorative items from various metals.'},
          {name: 'Polder Builders', emoji: '🏞️', description: 'Masters of reclaiming land from the sea or lakes through the construction of dikes and drainage systems for agriculture.'},
          {name: 'Industrious Labor', emoji: '🏭', description: 'Characterized by diligence, hard work, and efficient production in all economic endeavors.'},
          {name: 'Expert Fishermen', emoji: '🎣', description: 'Highly skilled in various fishing techniques, capable of catching abundant marine life from diverse environments.'},
          {name: 'Prolific Hunters', emoji: '🦌', description: 'Excel at hunting and trapping wild game, providing a significant portion of their food and resources.'},
          {name: 'Vegetarian Diet', emoji: '🌿', description: 'Their diet and culinary traditions primarily revolve around plant-based foods, often for spiritual, ethical, or resource-based reasons.'},
          {name: 'Bush Hunting', emoji: '🐾', description: 'Specializes in tracking and hunting wild animals in dense bush and wilderness areas using traditional methods.'},
          {name: 'Elephant Handlers', emoji: '🐘', description: 'Utilizes elephants for labor, warfare, or ceremony, valuing and managing these animals as a key resource and symbol of power.'},
          {name: 'Irrigation Masters', emoji: '💧', description: 'Masters of designing and constructing complex irrigation systems to maximize agricultural output in arid or semi-arid regions.'},
          {name: 'Mountain Herding', emoji: '⛰️🐑', description: 'Practices animal husbandry adapted to mountainous terrain, utilizing high pastures for grazing and specialized livestock breeds.'},
          {name: 'Valley Traders', emoji: '🏞️', description: 'Specializes in traversing difficult terrain (e.g., mountains, dense forests) to connect distinct valleys for trade and cultural exchange.'},
        ]
      },
      {
        name: 'Arts & Craftsmanship',
        emoji: '🎨',
        color: '#8B5CF6',
        traditions: [
          {name: 'Master Artisans', emoji: '✨', description: 'Renowned for their highly skilled craftsmanship in various arts, with guilds protecting their secrets.'},
          {name: 'Castle Guardians', emoji: '🏰', description: 'Specializes in the construction, maintenance, and defense of fortified castles, central to their strategic defense.', opposite: 'City Defenders'},
          {name: 'City Defenders', emoji: '🏙️', description: 'Dedicated to the maintenance, development, and defense of urban centers, vital for trade and governance.', opposite: 'City Guardians'},
          {name: 'Temple Builders', emoji: '⛪', description: 'Known for constructing elaborate and numerous religious structures, showcasing devotion and power.'},
          {name: 'Mountain Dwellings', emoji: '🏡', description: 'Builds settlements and dwellings directly into or around mountains, utilizing natural defenses and materials.'},
          {name: 'Runestone Erectors', emoji: '🪨', description: 'Practices the tradition of erecting carved stones for commemoration or ritual, documenting history and beliefs.'},
          {name: 'Glassblowing Artisans', emoji: '💎', description: 'Skilled in the art of shaping glass into intricate objects and useful items, a prized and often traded craft.'},
          {name: 'Bridge Engineers', emoji: '🌉', description: 'Expertise in constructing bridges across rivers, chasms or other obstacles, facilitating travel and trade.'},
          {name: 'Master Stonecutters', emoji: '⚒️', description: 'Proficient in shaping and carving stone for construction, art, or tools, foundational to their monumental works.'},
          {name: 'Stonemason Guild', emoji: '🧱', description: 'A strong guild of stonemasons, maintaining high standards and traditions in monumental construction and artistry.'},
          {name: 'Thatch Builders', emoji: '🛖', description: 'Skilled in the art of building and repairing roofs with thatch, crucial for common dwellings and agricultural structures.'},
          {name: 'Mask Carving', emoji: '🎭', description: 'A significant tradition of carving masks for ritual, performance, or display, holding deep cultural meaning.'},
          {name: 'Bronze Sculpture', emoji: '🗿', description: 'Masters of intricate bronze statuary and decorative casting, creating effigies and ceremonial objects.'},
          {name: 'Cylinder Seal Art', emoji: '📜', description: 'Creates unique cylinder seals for administration, trade, and personal identification, a form of early security.'},
          {name: 'Garden Design', emoji: '🌳', description: 'Masters of designing and cultivating elaborate gardens, seen as high art and places of contemplation.'},
          {name: 'Culinary Arts', emoji: '🍲', description: 'Renowned for sophisticated cuisine and innovative cooking techniques, turning food preparation into a high art form.'},
          {name: 'Musical Theory', emoji: '🎼', description: 'Deeply invested in the academic study and philosophical understanding of music, developing complex theories and compositions.'},
          {name: 'Literary Arts', emoji: '📜', description: 'Highly values and practices sophisticated forms of poetry and literature, often recounting myths and heroic deeds.'},
          {name: 'Whistleblowers', emoji: '🌬️', description: 'Practices a vocal art form that mimics the sounds of wind and air, often used for evocative storytelling or guiding navigation by sound.'},
          {name: 'Oral Tradition', emoji: '🗣️', description: 'Highly values oral narratives, epic poems, and bards for preserving history, myths, and entertainment.'},
          {name: 'Festival of Lights', emoji: '💡', description: 'Celebrates a significant annual festival involving lights or illumination, often marking solstices or harvests.'},
        ]
      },
      {
        name: 'Spiritual & Knowledge',
        emoji: '📚',
        color: '#6366F1',
        traditions: [
          {name: 'Sacred Groves', emoji: '🌳', description: 'Designates and protects natural areas as places of spiritual significance, where rituals are performed.'},
          {name: 'Ancestral Spirits', emoji: '👻', description: 'Strong belief in the active presence and guidance of ancestral spirits, who influence daily life.'},
          {name: 'Weapon Blessings', emoji: '🪔', description: 'A ritual worship of weapons, particularly swords, often for martial blessing before battle.'},
          {name: 'Stargazers', emoji: '🔭', description: 'Practices astrology or astronomy for guidance, prophecy, or navigation, interpreting celestial signs.'},
          {name: 'Eyes Up', emoji: '☁️', description: 'Observes celestial phenomena for religious, navigational, or predictive purposes, noting cosmic patterns.'},
          {name: 'Ancestor Tablets', emoji: '🪦', description: 'Maintains carved or inscribed tablets to honor and remember ancestors, forming a core part of household worship.'},
          {name: 'Oral Historians', emoji: '🗣️', description: 'Preserves history, lore, and traditions primarily through spoken narratives, passed down through generations.'},
          {name: 'Mist Weavers', emoji: '🌫️', description: 'Possesses the ability or tradition of controlling or interacting with mist, often associated with hidden knowledge.'},
          {name: 'Devout Faith', emoji: '🛐', description: 'Deeply devout in their faith, with strong adherence to religious doctrines and a pervasive spiritual life.'},
          {name: 'Oracle Priesthood', emoji: '🔮', description: 'Relies on a specialized priesthood to interpret divine will and provide prophecies for important decisions.'},
          {name: 'Sacred Sacrifices', emoji: '🩸', description: 'Practices regular animal or sometimes human sacrifice to appease deities or ensure prosperity.'},
          {name: 'Temple Bureaucracy', emoji: '🏛️', description: 'Temples serve not only as religious centers but also as economic and administrative hubs.'},
          {name: 'Pantheon Worship', emoji: '🔱', description: 'Adheres to a complex polytheistic system with a hierarchy of gods and goddesses governing different aspects of life.'},
          {name: 'Scribal Lore', emoji: '✍️', description: 'A dedicated class of scribes preserves and interprets ancient texts, religious scripture, and historical records.'},
          {name: 'Dream Divination', emoji: '💭', description: 'Interprets dreams as divine omens or messages from spirits, guiding decisions.'},
          {name: 'Alliance Knotting Rites', emoji: '❤️💍', description: 'Marriage rituals are elaborate and central to social and spiritual life, often involving specific customs and blessings.'},
          {name: 'Herbalism', emoji: '🌿', description: 'Possesses extensive knowledge of local flora and their medicinal properties, providing traditional healing.'},
          {name: 'Wandering Mystics', emoji: '🚶✨', description: 'Spiritual practitioners who wander and rely on alms, spreading religious teachings or offering spiritual guidance.'},
          {name: 'Monastic Orders', emoji: '🧘', description: 'Significant portion of the population lives in secluded religious communities, contributing to spiritual and intellectual life.'},
          {name: 'Asnatii Xagals', emoji: '❄️📖', description: 'Their folklore and epic tales are deeply influenced by harsh northern climates, featuring sagas of endurance and survival.'},
          {name: 'Religious Syncretism', emoji: '🙏', description: 'A syncretic approach to faith, integrating elements from different religious traditions into a unique belief system.'},
          {name: 'Religious Patronage', emoji: '✨💰', description: 'The wealthy and powerful actively support religious institutions, art, and scholars, fostering spiritual development.'},
          {name: 'Sacred Hunts', emoji: '🦌🙏', description: 'Hunting is imbued with spiritual significance, performed with rituals and reverence for the hunted animals.'},
          {name: 'Sacred Mountains', emoji: '⛰️🙏', description: 'Mountains are revered as holy sites, often home to temples, shrines, or seen as dwelling places of deities.'},
          {name: 'Tactical Games', emoji: '🎲📚', description: 'A culture that values strategy and planning through board games and tactical simulations, often reflecting their military theory.'},
          {name: 'Water Rites', emoji: '💧🙏', description: 'Water bodies (rivers, lakes, springs) are central to spiritual practices, with rituals focused on cleansing, fertility, or blessings.'},
          {name: 'Learning Beacon', emoji: '💡', description: 'A society that serves as a center of knowledge and education, attracting scholars and fostering intellectual pursuits.'},
          {name: 'United by Faith', emoji: '🙏', description: 'Society is deeply unified by shared religious beliefs and practices, guiding all aspects of life.'},
          {name: 'Master Linguists', emoji: '🗣️📖', description: 'Possesses a strong tradition of studying and mastering multiple languages, often for trade, diplomacy, or scholarship.'},
          {name: 'Millenar Ceremonies', emoji: '🗓️✨', description: 'Engages in grand, rare ceremonies performed only once every thousand years, marking significant cosmic or historical cycles.'},
          {name: 'River Pilgrimage', emoji: '🛶', description: 'Undertakes spiritual journeys along rivers, often involving rituals or ceremonies at sacred water points.'},
        ]
      },
      {
        name: 'Environment & Lifestyle',
        emoji: '🏕️',
        color: '#14B8A6',
        traditions: [
          {name: 'Highland Lifestyle', emoji: '⛰️', description: 'A rural lifestyle adapted to mountainous regions, often isolated and self-sufficient, valuing independence.'},
          {name: 'Master Seafarers', emoji: '⛵', description: 'Primary way of life revolves around the sea, including fishing, trade, and exploration, with strong maritime skills.'},
          {name: 'Ice Harvesting', emoji: '🧊', description: 'Practices the gathering and storage of ice for preservation or other uses, crucial in colder climates.'},
          {name: 'Beast Tamers', emoji: '🐺', description: 'Skilled in taming and training various animals for work, combat, or companionship, forming strong bonds with creatures.'},
          {name: 'Twin Birth Rites', emoji: '👶👶', description: 'A specific ritual or set of beliefs associated with the birth of twins, often seen as a sacred or significant event.'},
          {name: 'Salt Mariners', emoji: '🧂', description: 'Navigators or traders specialized in the transportation or trade of salt, vital for preservation and diet.'},
          {name: 'Bell Rites', emoji: '🔔', description: 'A tradition involving the use of bells for communication, rituals, or celebration, signifying important events.'},
          {name: 'Floodplain Farmers', emoji: '🚜', description: 'Thrives by adapting agricultural practices to annual river floods, utilizing the fertile silt for abundant harvests.'},
          {name: 'Seasonal Shepherds', emoji: '🐑', description: 'Practices seasonal movement of livestock between fixed summer and winter pastures, optimizing grazing.'},
          {name: 'Wetland Lifestyle', emoji: '🛶', description: 'Skilled at harvesting resources and navigating marshy or wetland environments, utilizing unique flora and fauna.'},
          {name: 'Oasis Dwellers', emoji: '🌴', description: 'Successfully cultivates and lives around isolated water sources in arid lands, creating self-sustaining communities.'},
          {name: 'Burning Grove Settlers', emoji: '🔥', description: 'Expands agricultural land by systematically clearing and burning forested areas, transforming the landscape.'},
          {name: 'Marine Harvesters', emoji: '🐚', description: 'Skilled in exploiting coastal and shallow marine resources beyond just fishing (e.g., shellfish, seaweed), a diverse diet.'},
          {name: 'Forest Dweller Clan', emoji: '🌲', description: 'A people deeply connected to and living within dense forests, skilled in forest survival and traditions.'},
          {name: 'Hidden Settlements', emoji: '🌿🌃', description: 'Masters of constructing and concealing their settlements within natural landscapes like dense forests or deep valleys.'},
          {name: 'Master Falconers', emoji: '🦅', description: 'Highly skilled in training and hunting with falcons and other birds of prey, a valued part of their culture and hunting practices.'},
          {name: 'Desert Ribats', emoji: '🏜️🕌', description: 'Maintains a network of fortified desert outposts, serving as both military garrisons and spiritual centers, vital for controlling trade routes.'},
          {name: 'Desert Guides', emoji: '🐪🏜️', description: 'Experts in navigating vast desert expanses, renowned for their endurance and knowledge of hidden routes and water sources.'},
          {name: 'Fierce Independence', emoji: '🦅', description: 'Values freedom and self-determination above all, fiercely resisting external control or encroachment.'},
          {name: 'Horse Lords', emoji: '🐎👑', description: 'A nomadic or semi-nomadic culture whose society, economy, and military are centered around horses.'},
          {name: 'Pragmatic Ethic', emoji: '🛠️', description: 'Their beliefs and societal values prioritize practical results and efficiency over rigid dogma or idealistic principles.'}
        ]
      }
    ];
